sudo: true
language: python
python:
 - "3.5"
before_install:
  - sudo apt-get install unzip
  - curl https://codeload.github.com/prompto/prompto-tests/zip/master > prompto-tests.zip
  - unzip prompto-tests.zip
  - mv prompto-tests-master prompto-tests
  - curl https://codeload.github.com/prompto/prompto-libraries/zip/master > prompto-libraries.zip
  - unzip prompto-libraries.zip
  - mv prompto-libraries-master prompto-libraries
  - pip install antlr4==4.5.3
before_script:
  - chmod 777 ./test.sh
script:
  - ./test.sh